In [133]:
import numpy as np
import math

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; - не определены
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; - определены, размерность 2x3
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; - определены, размерность 8x8
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. - определены, размерность 4x4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [15]:
A = np.array([ [1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма \n {A+B}\nПроизведение \n {np.dot(A, B)}')

Сумма 
 [[ 5 -3]
 [ 3  5]]
Произведение 
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [18]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица AB\n{2*A - 2*B + 4*C}')

Матрица AB
[[ 10 -12]
 [  6  -6]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [49]:
A2 = np.array([[4, 1], [5, -2], [2, 3]])
print(f'1 \n {np.dot(A2.T, A2)}\n2 \n{np.dot(A2, A2.T)}') 

1 
 [[45  0]
 [ 0 14]]
2 
[[17 18 11]
 [18 29  4]
 [11  4 13]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
Условия:
количество столбцов первой матрицы должно быть =  количеству строк второй при перемножении.
m1 = n2

In [120]:
n1 = int(input ('Введите количество строк первой матрицы '))
m1 = int(input ('Введите количество столбцов первой матрицы '))
n2 = int(input ('Введите количество строк второй матрицы '))
m2 = int(input ('Введите количество столбцов второй матрицы '))

Введите количество строк первой матрицы 3
Введите количество столбцов первой матрицы 4
Введите количество строк второй матрицы 4
Введите количество столбцов второй матрицы 3


In [118]:
def creatematrix(r,c):
    t=[]
    m=[]
    for i in range(r):
        for j in range(c):
            t.append(random.randint(1,10))
        m.append(t)
        t=[]
    return m

In [121]:
m1=creatematrix(n1,m1)
m2=creatematrix(n2,m2)

In [125]:
def matrixmult(m1,m2):
    s=0   #сумма
    t=[]  #временная матрица
    m3=[] #конечная матрица
    if len(m2)!=len(m1[0]):
        print ("Матрицы не могут быть перемножены")        
    else:
        r1=len(m1) #количество строк в первой матрице
        c1=len(m1[0]) #количество столбцов в первой матрице  
        r2=c1           #количество строк во второй матрице
        c2=len(m2[0])  #количество столбцов во второй матрице
        for z in range(r1):
            for j in range(c2):
                for i in range(c1):
                    s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
    return m3

In [126]:
matrixmult(m1,m2)

[[128, 76, 110], [105, 60, 110], [86, 55, 63]]

**Практическое задание часть 2**

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

Вычисляем по формуле:
$$\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

$$ sin(x)^2 + cos(x)^2 =1 $$

b)
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

Вычисляем по формуле:

$$detA = \sum_{i=1}^{n}(-1)^{i+j}a_{ij}M_{ij},$$

а лучше по инструкции первой строки вычисления миноров с учетом матрицы знаков http://mathprofi.ru/kak_vychislit_opredelitel.html

$$4 \begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 
2 \begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix} + 
3 \begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix} = 4 \cdot(5\cdot9 - 0\cdot1) - 2 \cdot (0\cdot9 - 0 \cdot 1) + 3 \cdot (0\cdot0 - 5\cdot0 ) = 180$$

In [134]:
#Проверям 
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

In [146]:
B = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
C = np.linalg.matrix_power(B, 2)
G = 2*B
print (np.linalg.det(B), np.linalg.det(G))

0.0 0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$; ответ 16
    
   б) $det(A^{T})$; ответ 4
    
   в) $det(2A)$. опытным путем примерно 4*8 = 32


   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная. Определитель матрицы = 0, поэтому она является сингулярной или вырожденной

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Ранг матрицы = 2, так как мы можем линейно выразить третью строку через первый 2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

выкинем третью строку, так как она линейно выражается через первую и вторую

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

вычтем из второй строки первую

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$


ранг матрицы равен  3, так строчный ранг матрицы всегда совпадает с столбцовым 

In [157]:
#Проверяем по коду
ma = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(ma)

3